volumes:
  postgres_data:
  redis_data:
  go_mods:
  go_tools:
  go_bin:
  vite_deps:

services:
  genshinquiz-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - ./backend/openapi:/app/openapi # 挂载 openapi 文件夹
      - vite_deps:/app/node_modules/.vite # 挂载 Vite 依赖缓存
    environment:
      VITE_API_URL: http://localhost:8080/api/v1
      CHOKIDAR_USEPOLLING: true
    depends_on:
      - genshinquiz-backend
    command: /bin/sh -c "bun install && bun run dev:docker"
    profiles: ["genshinquiz"]

  # Go Backend API
  genshinquiz-backend:
    image: golang:1.25-alpine
    # build:
    #   context: ./backend
    #   dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    working_dir: /app
    environment:
      GOBIN: /app/bin
      DATABASE_URL: "postgres://postgres:postgres@postgres:5432/genshinquiz?sslmode=disable"
      REDIS_HOST: redis
    volumes:
      - ./backend:/app
      - go_mods:/go/pkg/mod
      - go_bin:/app/bin
    entrypoint:
      - /bin/sh
      - -c
      - |
        if [ ! -f /usr/local/bin/task ]; then
          curl -sL https://taskfile.dev/install.sh | sh -s -- -b /usr/local/bin
        fi
        if ! command -v psql &> /dev/null; then
          apt update && apt install -y postgresql-client && apt clean
        fi
        task init-env
        if [ ! -f /app/bin/goose ]; then
          go install github.com/pressly/goose/v3/cmd/goose@latest
        fi
        task db-migration-up
        task run-server
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8080/health",
        ]
      interval: 30s
      retries: 3
      timeout: 10s
      start_period: 40s
    profiles: ["genshinquiz"]

  moe-link:
    build:
      context: ./moe-link
    ports:
      - "3080:3080"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - ./frontend/openapi:/app/openapi # 挂载 openapi 文件夹
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    command: /bin/sh -c "npm run dev" # 运行 Orval 生成代码然后启动 Bun 开发服务器
    profiles: ["moe-link"]

  vue-home:
    build:
      context: ./vue-home
    ports:
      - "3081:3081"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - ./frontend/openapi:/app/openapi # 挂载 openapi 文件夹
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    command: /bin/sh -c "npm run dev" # 运行 Orval 生成代码然后启动 Bun 开发服务器
    profiles: ["moe-link"]

  alpha-soul:
    build:
      context: ./alpha-soul
    ports:
      - "3083:3083"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - ./frontend/openapi:/app/openapi # 将 openapi 文件夹挂载到容器内的 /app/openapi
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    command: /bin/sh -c "npm run dev" # 运行 Orval 生成代码然后启动 Bun 开发服务器
    profiles: ["moe-link"]

  node-api:
    build:
      context: ./node-api
    ports:
      - "3082:3082"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./frontend/openapi:/app/openapi # 将 openapi 文件夹挂载到容器内的 /app/openapi
    depends_on:
      - database
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=genshinquiz
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:3082/"]
      interval: 30s
      retries: 3
      timeout: 10s
      start_period: 5s
    command: /bin/sh -c "npm install && node index.js"
    profiles: ["moe-link"]

  # PostgreSQL Database
  postgres:
    container_name: postgres
    image: postgres:16.4
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: exampledb
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
    profiles: ["genshinquiz", "moe-link"]

  # Redis Cache and Queue
  redis:
    container_name: redis
    image: redis:7.2-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    profiles: ["genshinquiz", "moe-link"]
