openapi: 3.0.0
info:
  title: Simple API
  description: A simple API example
  version: 1.0.0

servers:
  - url: http://localhost:3082/api
    description: Local server

paths:
  /greet:
    get:
      summary: Greet the user
      description: Returns a greeting message
      operationId: greetUser
      responses:
        '200':
          description: A greeting message
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Hello, world!"
