/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * GenshinQuiz API
 * API for Quiz system
 * OpenAPI spec version: 1.0.0
 */
export interface Quiz {
  id: string;
  quiz: string;
  options: string[];
  creator: string;
  creatAt: string;
  updateAt: string;
  multiple?: boolean;
  answer: string[];
}

export type BadRequestResponse = {
  error?: string;
};

export type UnauthorizedResponse = {
  error?: string;
};

export type GreetUser200 = {
  message?: string;
};

export type GetRandomQuiz200 = {
  quiz?: Quiz;
};

export type GetQuizsParams = {
/**
 * pagination
 */
page?: number;
/**
 * tags
 */
tags?: string;
/**
 * authors
 */
authors?: string;
};

export type GetQuizs200 = {
  quizzes: Quiz[];
  count: number;
};

export type GetQuizQuizid200 = {
  quiz?: Quiz;
};

